spring:
  application:    name: security-service
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
      file-size-threshold: 20KB  datasource:
    hikari:
      connection-timeout: 6000
      maximum-pool-size: 200
      data-source-properties:
        cachePrepStmts: true
        prepStmtCacheSize: 250
        useServerPrepStmts: true
        prepStmtCacheSqlLimit: 2048
  jpa:    show-sql: true
springdoc:  swagger-ui:    disable-swagger-default-url: true
eureka:
  client:
   serviceUrl:
    defaultZone: ${EUREKA_URI:http://localhost:8761/eureka/}
logging:
  level:
    root: info
---
server:
  port: 9080
spring:
  profiles: dev
  datasource:    url: jdbc:mariadb://192.168.1.10:3306/vtracking
    username: admin
    password: Admin123
    driver-class-name: org.mariadb.jdbc.Driver
eureka:
  client:
    registerWithEureka: false
    fetchRegistry: false
---
server:
  port: 0
spring:
  profiles: prod
  datasource:
    url: jdbc:mariadb://${DB_HOST}:${DB_PORT}/${DB_SERVICE_NAME}
    username: ${DB_USER_NAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.mariadb.jdbc.Driver